"use strict";

const { createConversationService } = require("./services/conversation_service");
const { createControlService } = require("./services/control_service");
const { createHarnessAppService } = require("./services/harness_app_service");
const { createEvalService } = require("./services/eval_service");
const { createExecService } = require("./services/exec_service");
const { createOverviewService } = require("./services/overview_service");
const { createReplayService } = require("./services/replay_service");

function createRouteServices(deps) {
  const overviewService = createOverviewService({
    sendJson: deps.sendJson,
    buildIntentFirstApiSnapshot: deps.buildIntentFirstApiSnapshot,
    buildHarnessOverviewSnapshot: deps.buildHarnessOverviewSnapshot,
    getConversationRuntimeSnapshot: deps.getConversationRuntimeSnapshot,
    normalizeConversationPersonaUserId: deps.normalizeConversationPersonaUserId,
    getConversationPersonaContextForUser: deps.getConversationPersonaContextForUser,
    getAgentTopographySnapshot: deps.getAgentTopographySnapshot,
    inspectContinuityTask: deps.inspectContinuityTask,
    workspaceRoot: deps.workspaceRoot,
    safeString: deps.safeString,
    getDiagnosticsSnapshot: deps.getDiagnosticsSnapshot,
    buildSloRuntimeSnapshot: deps.buildSloRuntimeSnapshot,
    maybeEmitSloAlert: deps.maybeEmitSloAlert,
  });

  const controlService = createControlService({
    validateControlMutationRequest: deps.validateControlMutationRequest,
    sendJson: deps.sendJson,
    validateJsonMutationContentType: deps.validateJsonMutationContentType,
    execApiRequiredContentType: deps.execApiRequiredContentType,
    readRequestBody: deps.readRequestBody,
    defaultRequestBodyLimitBytes: deps.defaultRequestBodyLimitBytes,
    safeString: deps.safeString,
    updateIntentProfileStore: deps.updateIntentProfileStore,
    resetIntentProfileStore: deps.resetIntentProfileStore,
    lockWorkspaceDirectory: deps.lockWorkspaceDirectory,
    unlockWorkspaceDirectory: deps.unlockWorkspaceDirectory,
    requirementGuardMatcherDefaults: deps.requirementGuardMatcherDefaults,
    evaluateRequirementGuardMatch: deps.evaluateRequirementGuardMatch,
    getRequirementGuardMatcherSnapshot: deps.getRequirementGuardMatcherSnapshot,
    requirementGuardExtensionConfig: deps.requirementGuardExtensionConfig,
    requirementGuardOriginalRequirement: deps.requirementGuardOriginalRequirement,
    openCmdWindowEnabled: deps.openCmdWindowEnabled,
    logOperation: deps.logOperation,
    requestHeaderValue: deps.requestHeaderValue,
    controlApiTokenHeaderName: deps.controlApiTokenHeaderName,
    openCmdWindow: deps.openCmdWindow,
    requestHarnessServerRestart: deps.requestHarnessServerRestart,
  });

  const conversationService = createConversationService({
    validateLocalOriginRequest: deps.validateLocalOriginRequest,
    logOperation: deps.logOperation,
    safeString: deps.safeString,
    requestHeaderValue: deps.requestHeaderValue,
    sendJson: deps.sendJson,
    validateJsonMutationContentType: deps.validateJsonMutationContentType,
    conversationApiRequiredContentType: deps.conversationApiRequiredContentType,
    readRequestBody: deps.readRequestBody,
    piperVoiceRequestBodyLimitBytes: deps.piperVoiceRequestBodyLimitBytes,
    normalizeBooleanFlag: deps.normalizeBooleanFlag,
    defaultPiperModelId: deps.defaultPiperModelId,
    nowTs: deps.nowTs,
    preparePiperModel: deps.preparePiperModel,
    workspaceRoot: deps.workspaceRoot,
    resolvePiperVoiceRequestErrorStatus: deps.resolvePiperVoiceRequestErrorStatus,
    summarizeErrorForOperationLog: deps.summarizeErrorForOperationLog,
    speakWithPiper: deps.speakWithPiper,
    kokoroVoiceRequestBodyLimitBytes: deps.kokoroVoiceRequestBodyLimitBytes,
    kokoroDefaultModel: deps.kokoroDefaultModel,
    kokoroDefaultVoice: deps.kokoroDefaultVoice,
    kokoroDefaultLangCode: deps.kokoroDefaultLangCode,
    requestKokoroSpeech: deps.requestKokoroSpeech,
    resolveKokoroVoiceRequestErrorStatus: deps.resolveKokoroVoiceRequestErrorStatus,
    conversationRequestBodyLimitBytes: deps.conversationRequestBodyLimitBytes,
    normalizeConversationMessage: deps.normalizeConversationMessage,
    normalizeConversationMode: deps.normalizeConversationMode,
    normalizeConversationPersonaUserId: deps.normalizeConversationPersonaUserId,
    normalizeConversationLevel: deps.normalizeConversationLevel,
    normalizeConversationTopic: deps.normalizeConversationTopic,
    normalizeConversationHistoryItems: deps.normalizeConversationHistoryItems,
    getConversationPersonaContextForUser: deps.getConversationPersonaContextForUser,
    conversationProvider: deps.conversationProvider,
    conversationAppServerModel: deps.conversationAppServerModel,
    summarizeTextForOperationLog: deps.summarizeTextForOperationLog,
    runConversationViaAppServer: deps.runConversationViaAppServer,
    updateConversationPersonaMemoryForUser: deps.updateConversationPersonaMemoryForUser,
    resolveConversationRequestErrorStatus: deps.resolveConversationRequestErrorStatus,
    conversationRequestTimeoutMs: deps.conversationRequestTimeoutMs,
    defaultRequestBodyLimitBytes: deps.defaultRequestBodyLimitBytes,
    resetConversationPersonaMemoryForUser: deps.resetConversationPersonaMemoryForUser,
    isRequestBodyTooLargeError: deps.isRequestBodyTooLargeError,
  });

  const harnessAppService = createHarnessAppService({
    validateLocalAppBridgeRequest: deps.validateLocalAppBridgeRequest,
    sendJson: deps.sendJson,
    validateJsonMutationContentType: deps.validateJsonMutationContentType,
    conversationApiRequiredContentType: deps.conversationApiRequiredContentType,
    getRegisteredAppRuntimeConfig: deps.getRegisteredAppRuntimeConfig,
    readRequestBody: deps.readRequestBody,
    defaultRequestBodyLimitBytes: deps.defaultRequestBodyLimitBytes,
    safeString: deps.safeString,
    normalizeExecModel: deps.normalizeExecModel,
    conversationExecModelName: deps.conversationExecModelName,
    normalizeAppRuntimeTimeoutMs: deps.normalizeAppRuntimeTimeoutMs,
    conversationRequestTimeoutMs: deps.conversationRequestTimeoutMs,
    resolveAppRuntimeWorkingDirectory: deps.resolveAppRuntimeWorkingDirectory,
    nowTs: deps.nowTs,
    runCodexReply: deps.runCodexReply,
    runCodexStructuredOutput: deps.runCodexStructuredOutput,
  });

  const evalService = createEvalService({
    validateControlMutationRequest: deps.validateControlMutationRequest,
    sendJson: deps.sendJson,
    evalRunHistoryMaxLines: deps.evalRunHistoryMaxLines,
    readEvalRunHistory: deps.readEvalRunHistory,
    summarizePathForOperationLog: deps.summarizePathForOperationLog,
    evalRunHistoryPath: deps.evalRunHistoryPath,
    validateJsonMutationContentType: deps.validateJsonMutationContentType,
    execApiRequiredContentType: deps.execApiRequiredContentType,
    readRequestBody: deps.readRequestBody,
    defaultRequestBodyLimitBytes: deps.defaultRequestBodyLimitBytes,
    defaultEvalSuite: deps.defaultEvalSuite,
    normalizeEvalSuite: deps.normalizeEvalSuite,
    safeString: deps.safeString,
    loadAgiV1ProfileConfig: deps.loadAgiV1ProfileConfig,
    workspaceRoot: deps.workspaceRoot,
    defaultExecAgentName: deps.defaultExecAgentName,
    defaultExecModelName: deps.defaultExecModelName,
    normalizeEvalVariant: deps.normalizeEvalVariant,
    expandAgiV1Variants: deps.expandAgiV1Variants,
    evalDefaultMaxVariants: deps.evalDefaultMaxVariants,
    evalMaxCases: deps.evalMaxCases,
    evalCaseTimeoutMs: deps.evalCaseTimeoutMs,
    normalizeBooleanFlag: deps.normalizeBooleanFlag,
    evalLanePolicy: deps.evalLanePolicy,
    assertEvalLaneAccess: deps.assertEvalLaneAccess,
    crypto: deps.crypto,
    captureManifestSnapshot: deps.captureManifestSnapshot,
    executeEvalVariantOnSuite: deps.executeEvalVariantOnSuite,
    persistHarnessExecutionMemoryStore: deps.persistHarnessExecutionMemoryStore,
    syncGovernedMemoryGraphFromLiveRuntime: deps.syncGovernedMemoryGraphFromLiveRuntime,
    logOperation: deps.logOperation,
    summarizeErrorForOperationLog: deps.summarizeErrorForOperationLog,
    compareEvalRuns: deps.compareEvalRuns,
    buildIndependentVerifierReport: deps.buildIndependentVerifierReport,
    buildCandidateBundle: deps.buildCandidateBundle,
    loadAgiBundleFromPath: deps.loadAgiBundleFromPath,
    path: deps.path,
    buildEvalRunGovernanceBundle: deps.buildEvalRunGovernanceBundle,
    adoptionReadinessContract: deps.adoptionReadinessContract,
    iterationControlContract: deps.iterationControlContract,
    buildReleaseDecision: deps.buildReleaseDecision,
    buildEvalSuiteSummary: deps.buildEvalSuiteSummary,
    appendEvalRunHistory: deps.appendEvalRunHistory,
    summarizeEvalLane: deps.summarizeEvalLane,
    harnessMemoryPath: deps.harnessMemoryPath,
  });

  const replayService = createReplayService({
    fs: deps.fs,
    path: deps.path,
    validateControlMutationRequest: deps.validateControlMutationRequest,
    sendJson: deps.sendJson,
    listReplayMemorySnapshots: deps.listReplayMemorySnapshots,
    getReplayMemoryRecord: deps.getReplayMemoryRecord,
    buildReplayMemorySnapshot: deps.buildReplayMemorySnapshot,
    safeString: deps.safeString,
    validateJsonMutationContentType: deps.validateJsonMutationContentType,
    execApiRequiredContentType: deps.execApiRequiredContentType,
    readRequestBody: deps.readRequestBody,
    defaultRequestBodyLimitBytes: deps.defaultRequestBodyLimitBytes,
    normalizeExecutionProfile: deps.normalizeExecutionProfile,
    isReproExecutionProfile: deps.isReproExecutionProfile,
    normalizeSandboxMode: deps.normalizeSandboxMode,
    normalizeApprovalPolicy: deps.normalizeApprovalPolicy,
    normalizeBooleanFlag: deps.normalizeBooleanFlag,
    normalizeExecModel: deps.normalizeExecModel,
    normalizeExecModelReasoningEffort: deps.normalizeExecModelReasoningEffort,
    normalizeAgentName: deps.normalizeAgentName,
    normalizeWorkingDirectory: deps.normalizeWorkingDirectory,
    normalizeCodexMemoryMode: deps.normalizeCodexMemoryMode,
    workspaceRoot: deps.workspaceRoot,
    normalizeRequestUserInputPolicy: deps.normalizeRequestUserInputPolicy,
    normalizeExecutionIntent: deps.normalizeExecutionIntent,
    crypto: deps.crypto,
    evalCaseTimeoutMs: deps.evalCaseTimeoutMs,
    runInternalExecRequest: deps.runInternalExecRequest,
    buildReplayDiffMetrics: deps.buildReplayDiffMetrics,
    updateReplayMemoryStats: deps.updateReplayMemoryStats,
    hashSha256Hex: deps.hashSha256Hex,
    getAppServerCapabilitySnapshot: deps.getAppServerCapabilitySnapshot,
  });

  const execService = createExecService({
    validateControlMutationRequest: deps.validateControlMutationRequest,
    logOperation: deps.logOperation,
    safeString: deps.safeString,
    requestHeaderValue: deps.requestHeaderValue,
    controlApiTokenHeaderName: deps.controlApiTokenHeaderName,
    sendJson: deps.sendJson,
    normalizeIdempotencyKey: deps.normalizeIdempotencyKey,
    normalizeExecIdempotencyWaitMs: deps.normalizeExecIdempotencyWaitMs,
    waitForExecIdempotencyRecord: deps.waitForExecIdempotencyRecord,
    buildExecIdempotencySnapshot: deps.buildExecIdempotencySnapshot,
    getLatestTurnSnapshot: deps.getLatestTurnSnapshot,
    validateJsonMutationContentType: deps.validateJsonMutationContentType,
    execApiRequiredContentType: deps.execApiRequiredContentType,
    readRequestBody: deps.readRequestBody,
    execRequestBodyLimitBytes: deps.execRequestBodyLimitBytes,
    extractExecIdempotencyKey: deps.extractExecIdempotencyKey,
    defaultPromptCharLimit: deps.defaultPromptCharLimit,
    normalizeSandboxMode: deps.normalizeSandboxMode,
    normalizeApprovalPolicy: deps.normalizeApprovalPolicy,
    normalizeWebSearchMode: deps.normalizeWebSearchMode,
    normalizeBooleanFlag: deps.normalizeBooleanFlag,
    resolveFastModeEnabled: deps.resolveFastModeEnabled,
    resolveAutomaticApprovalReviewEnabled: deps.resolveAutomaticApprovalReviewEnabled,
    normalizeExecModel: deps.normalizeExecModel,
    defaultExecModelName: deps.defaultExecModelName,
    normalizeExecModelReasoningEffort: deps.normalizeExecModelReasoningEffort,
    defaultExecModelReasoningEffort: deps.defaultExecModelReasoningEffort,
    normalizeAgentName: deps.normalizeAgentName,
    normalizeWorkingDirectory: deps.normalizeWorkingDirectory,
    workspaceRoot: deps.workspaceRoot,
    normalizeChatImageAttachments: deps.normalizeChatImageAttachments,
    normalizeRequestUserInputPolicy: deps.normalizeRequestUserInputPolicy,
    normalizeCodexMemoryMode: deps.normalizeCodexMemoryMode,
    nonInteractiveRequestUserInputPolicy: deps.nonInteractiveRequestUserInputPolicy,
    normalizeExecutionProfile: deps.normalizeExecutionProfile,
    runtimeExecutionProfile: deps.runtimeExecutionProfile,
    normalizeExecutionIntent: deps.normalizeExecutionIntent,
    resolveWorkspaceGuardRequirement: deps.resolveWorkspaceGuardRequirement,
    getWorkspaceGuardLockedRoot: deps.getWorkspaceGuardLockedRoot,
    buildWorkspaceGuardSnapshot: deps.buildWorkspaceGuardSnapshot,
    getOrCreateAgentState: deps.getOrCreateAgentState,
    derivePreviousPlanningContextForRequest: deps.derivePreviousPlanningContextForRequest,
    applyRequirementGuardExecExtension: deps.applyRequirementGuardExecExtension,
    buildPromptAudit: deps.buildPromptAudit,
    resolveAgentName: deps.resolveAgentName,
    validateRequestedAgentName: deps.validateRequestedAgentName,
    isReproExecutionProfile: deps.isReproExecutionProfile,
    extractGovernanceOverride: deps.extractGovernanceOverride,
    normalizeOverrideRequest: deps.normalizeOverrideRequest,
    buildWorkspaceGuardViolation: deps.buildWorkspaceGuardViolation,
    summarizePathForOperationLog: deps.summarizePathForOperationLog,
    summarizeTextForOperationLog: deps.summarizeTextForOperationLog,
    claimExecIdempotencyKey: deps.claimExecIdempotencyKey,
    hashSha256Hex: deps.hashSha256Hex,
    resolveExecTerminalStatusFromSnapshot: deps.resolveExecTerminalStatusFromSnapshot,
    isResolvedExecLifecycleState: deps.isResolvedExecLifecycleState,
    isSuccessfulExecTerminalStatus: deps.isSuccessfulExecTerminalStatus,
    incrementActiveExecRequestCount: deps.incrementActiveExecRequestCount,
    decrementActiveExecRequestCount: deps.decrementActiveExecRequestCount,
    finalizeExecIdempotencyKey: deps.finalizeExecIdempotencyKey,
    markExecIdempotencyResponseClosed: deps.markExecIdempotencyResponseClosed,
    runCodexExecStreaming: deps.runCodexExecStreaming,
    writeChunk: deps.writeChunk,
    releaseExecIdempotencyKey: deps.releaseExecIdempotencyKey,
    resolveExecRequestErrorStatus: deps.resolveExecRequestErrorStatus,
    summarizeErrorForOperationLog: deps.summarizeErrorForOperationLog,
  });

  return Object.freeze({
    overview: overviewService,
    control: controlService,
    harnessApp: harnessAppService,
    conversation: conversationService,
    replay: replayService,
    eval: evalService,
    exec: execService,
  });
}

module.exports = {
  createRouteServices,
};
